server:
  port: 9092

spring:
  dubbo:
    application:
      name: dubboProvider
    registry: #注册中心配置，用于配置连接注册中心相关信息
      address: zookeeper://127.0.0.1:2181
    protocol: #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
      name: dubbo
      port: 20881

